version: "3.8"
services:
  db:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
